Cedar.xcodeproj/project.pbxproj, Source/CDRNil.m, Source/CDRTypeUtilities.m, Source/Headers/CDRNil.h, Spec/CDRNilSpec.mm, Spec/CDRTypeUtilitiesSpec.mm, Spec/Doubles/HaveReceivedSpec.mm
This is my take on fixing #306. @akitchen I just worked off the failing test case you had pushed. If you have a superior solution, let's use that.
=> Fix reporting of sent-messages history containing a `nil` argument

Cedar.xcodeproj/project.pbxproj
- i.e. rather than using the system Ruby, it will use the Ruby from rbenv
Signed-off-by: Eugenia Dellapenna <edellapenna@pivotal.io>
=> Updates ruby path for set git SHA so that it uses the current Ruby version

Source/Headers/Doubles/Arguments/ValueArgument.h, Spec/Doubles/CedarDoubleSharedExamples.mm, Spec/Support/SimpleIncrementer.h, Spec/Support/SimpleIncrementer.m
Slightly amended version of #312 which removes an unnecessary call to both_are_objects.
Credit to @joemasilotti for finding and reporting this bug.
=> Allow stubbing & expectation for pointer arguments

Cedar.xcodeproj/project.pbxproj, CedarPlugin.xcplugin/Contents/Info.plist, Spec/Matchers/Base/BeGTESpec.mm, Spec/Matchers/Base/BeGreaterThanSpec.mm, Spec/Matchers/Base/BeLTESpec.mm, Spec/Matchers/Base/BeLessThanSpec.mm
Updates the bundled Cedar Xcode Plugin's DVTPlugInCompatibilityUUID list and disables some specs which fail to compile with the latest toolchain due to increased strictness.  More work is needed in order to continue to support ```expect(667) >= 666;```
=> Xcode 6.3 Compatibility

Source/CDRSpec.m, Spec/SpecSpec.mm
This can occur by accidentally forgetting to create an `it` block before writing the assertion.
I've seen people encounter this a few times and get very confused. Because any `beforeEach` blocks won't have run to set up context, even a simple assertion is likely to fail.
=> Print a helpful message if a matcher fails while setting up specs.

CodeSnippetsAndTemplates/Templates/File Templates/Cedar/Cedar Spec.xctemplate/TemplateInfo.plist, CodeSnippetsAndTemplates/Templates/File Templates/Cedar/Cedar Spec.xctemplate/___FILEBASENAME___Spec.mm
Untested with earlier versions of xcode.
Apparently in Xcode 6.3 the TemplateInfo.plist has a version of the macros that
xcode provides (e.g.:: `___FILENAMEBASE___`) that are different from the contents of
the template. The template contents use the *actual* file name, rather than what the
user provides.
This fix just captures the class the user typed as a variable, and then uses it
in the template. I believe this should work on earlier versions of Xcode, but
I haven't had the liberty to check yet.
Fixes #324
=> Update templates to work with Xcode 6.3

Source/Headers/Matchers/Base/BeSameInstanceAs.h, Spec/Matchers/Base/BeSameInstanceAsSpec.mm
@wileykestner discovered this on our project this morning. Our understanding of the `be_same_instance_as` matcher is that it helps users verify that their objects are actually the correct instance of their objects they created under test. We had a scenario where we  had failed to actually setup our test objects, and our tests passed before we had wrote a single line of code.
```objc
describe("a passing test", ^{
__block MyDependency *dependency;
__block MyClass *subject;
beforeEach(^{
subject = [[MyClass alloc] initWithDependency:dependency];
});
it(@"should not be passing yet, but it does", ^{
subject.dependency should be_same_instance_as(dependency);
});
});
```
Unfortunately, this is a non-backwards compatible change, since it changes the contract of `be_same_instance_as`.
=> be_same_instance_as matcher should not match nil values

Cedar.xcodeproj/xcshareddata/xcschemes/Cedar OS X Host App.xcscheme, Cedar.xcodeproj/xcshareddata/xcschemes/Cedar iOS XCTest Tests.xcscheme, Spec/CDRSpecFailureSpec.mm, Spec/Doubles/CedarDoubleARCSharedExamples.mm
Here are a few updates for Xcode 7 - the compilation fixes expose failing tests in the symbolicator, which we probably need to look into.
This is harmless to merge for Xcode 6.3, but full Xcode 7 compatibility requires a bit more work, or at least investigation.
See also #333 , which will require some refactoring.
=> Xcode7 compilation updates

README.markdown
As suggested in #337. Let's not merge this until that work has been rebased and put onto the `Xcode7` branch.
=> Mention the existence of the Xcode7 branch in the README

Source/Headers/Cedar.h
This seems like an easy way to reduce the pain that future users will inevitably have when inadvertently importing Cedar in places where it doesn't belong. (Cf. #341)
Any objections?
=> Produce an explicit error if Cedar is imported from a non-C++ source file

Source/Doubles/CDRFake.mm, Source/Doubles/CDRSpy.mm, Source/Doubles/CedarDoubleImpl.mm, Source/Headers/Doubles/CedarDouble.h, Spec/Doubles/CedarDoubleSharedExamples.mm
This allows you to ask the double for all invocations that exactly match
a given selector.
This is something that I've often had to write my own code for which
iterates through invocations and plucks out the correct ones.
=> Adds -sent_messages_with_selector: to <CedarDouble>

Source/Extensions/NSMethodSignature+Cedar.m, Spec/Doubles/CedarDoubleSharedExamples.mm, Spec/Support/SimpleIncrementer.h
This happens for methods that take a block parameter that takes an object specified with a protocol.
=> Fix crash when adding a block stub to certain methods

Cedar.xcodeproj/project.pbxproj, Source/CDRFunctions.m, scripts/set_git_sha_on_framework.rb
- No more `(null)` output when building against the static lib
- Share a common script between targets for copying the git SHA into the Info.plist
=> Clean up version reporting

Source/Headers/Project/XCTest/CDRXCTestSupport.h, Source/XCTest/CDRXCTestFunctions.m
I'm hoping to play with this a little more to get more confidence in this change, but this seems to be a simple way to get to `xctool` find and execute Cedar specs. It turns out that `xctool` calls `+[XCTestSuite allTests]` when gathering the available tests. This method isn't in the public interface, but is what `+[XCTestSuite defaultTestSuite]` delegates to for doing all its work.
CC folks involved in #308 and facebook/xctool#417 - please give this a try!
@parse @haskelash @adamhrz
=> Adjust XCTest integration such that xctool finds Cedar specs

Cedar.podspec
It seems that when Cocoapods Trunk generated the JSON representation of the podspec for the last release, the tvOS platform support didn't get included. Now that tvOS support is included in the public Cocoapods release, we can remove the conditional and cut a patch release.
=> Remove conditional from the tvOS declaration in the podspec

Cedar.xcodeproj/project.pbxproj, Source/Headers/Public/Matchers/CedarMatchers.h, Source/Headers/Public/Matchers/Container/ContainSubset.h, Spec/Matchers/Container/ContainSubsetSpec.mm
This matcher can be used to check if a NSDictionary contains another NSDictionary as a subset.
We tried to clean up the implementation of `matches` as much as possible, but it was hard to keep the generic method that accepts any type and have overloaded implementations for `NSDictionary *` that don't need to do the validation. Perhaps someone has some feedback on how this could be done better?
=> Add contain_subset matcher

Cedar.xcodeproj/project.pbxproj, Cedar.xcodeproj/xcshareddata/xcschemes/Cedar-tvOS SpecBundle.xcscheme, Cedar.xcodeproj/xcshareddata/xcschemes/Cedar-tvOS.xcscheme, Source/Headers/Public/Matchers/Base/BlockMatcher.h, Source/Headers/Public/Matchers/CedarMatchers.h, Spec/Matchers/Base/BlockMatcherSpec.mm, Spec/Matchers/Base/BlockMatcher_ARCSpecSpec.mm
On my current project, there have been a couple instances recently where my tests were really calling for a nice domain-specific matcher, but I decided not to write one because I didn't want to have to deal with creating a new C++ type, remembering how the Base matcher works, etc., so I decided to see what I could do about providing a simpler mechanism for doing this.
I came up with this BlockMatcher interface which I am reasonably, although not entirely, happy with. Its usage looks like this:
```objective-c
// Defined in your spec, or in a test helper somewhere:
CedarBlockMatcher be_a_palindrome = matcher(^(NSString *subject) {
subject = [subject lowercaseString];
return [subject isEqual:[subject reversedString]]; // -reversedString defined elsewhere
}).with_failure_message_end(@"be a …
```
=> Add a matcher for defining custom matchers using blocks

README.markdown
This pull requests corrects the spelling of **CocoaPods** 🤓
https://github.com/CocoaPods/shared_resources/tree/master/media
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">One day I’ll make a bot that looks through the READMEs of all Pods, looks to see if it uses “Cocoapods” and PRs “CocoaPods” :D</p>&mdash; Ørta (@orta) <a href="https://twitter.com/orta/status/697374357975388160">February 10, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
=> Correct the spelling of CocoaPods in README

Cedar.xcodeproj/project.pbxproj, Source/Headers/Project/XCTest/NSInvocation+CDRXExample.h, Source/XCTest/CDRSpec+XCTestSupport.m, Source/XCTest/CDRXCTestCase.m, Source/XCTest/NSInvocation+CDRXExample.m, Spec/Support/TestReporter.h, Spec/Support/TestReporter.m, Spec/XCTest/CDRXCTestSuiteSpec.mm
This modifies the way that Cedar integrates with the XCTest runner such that pending tests aren't ignored entirely, but are still made known to the example reporters. This results in the pending test count and summary info being included in Cedar's test output. The pending tests aren't exposed to XCTest, however, since there is no way to represent the "pending" state in its framework.
This addresses #303 and https://www.pivotaltracker.com/story/show/99707426.
(Inspired by a recent conversation with @pivotal/team-cedar, I also swapped the ad-hoc Cedar fake in `CDRXCTestSuiteSpec` with a full-fledged test double class.)
=> Pending tests should be printed when running under XCTest

Source/XCTest/CDRXCTestFunctions.m, Spec/SpecBundle/Support/TestObservationHelper.m
This is yet another fix to the test output issue raised by @cbguder 
While not as techically clean as #379 it does appear to fix it reliably.
=> Defer test observation center setup to fix Xcode 7.3 regression

Cedar.xcodeproj/project.pbxproj, Source/CDRFunctions.m, Source/CDRRunState.m, Source/CDRSpec.m, Source/CDRSpecRun.m, Source/CDRStateTracker.h, Source/CDRStateTracker.m, Source/CDRStateTracking.h, Source/CDRTypeUtilities.m, Source/Extensions/NSInvocation+Cedar.m, Source/Headers/Project/CDRRunState.h, Source/Headers/Project/CDRSpecRun.h, Source/Headers/Project/CDRTypeUtilities.h, Source/Headers/Public/CDRFunctions.h, Source/Headers/Public/CDRSpec.h, Source/XCTest/CDRXCTestFunctions.m, Spec/CDRExampleSpec.mm, Spec/CDRHooksSpec.mm, Spec/CDRSpecRunSpec.mm, Spec/CDRSymbolicatorSpec.mm, Spec/CDRTypeUtilitiesSpec.mm, Spec/Support/CedarTestSpecBuilder.h, Spec/Support/CedarTestSpecBuilder.m, Spec/XCTest/CDRXCTestSuiteSpec.mm
Fixes #394.
The first commit is the brunt of this feature work. DSL misuse encompasses two main failure modes:
* someone calls `it()`, `describe()`, or `context()` inside of an `it()` block
* this would never work because the newly-added tests are never run
* someone tries to call any of the above functions outside of a test
* this would never work because there is no spec yet to add them to until we build the tree
In writing this feature I tried to avoid adding much more scope to Cedar's public interface, but found it necessary to expose `CDRdisableSpecValidation()` and `CDRenableSpecValidation()` functions so that we could keep our existing tests that create cedar examples by calling `it()` inside of a test. I also thought it desirable to allow someone to disable this feature, if they …
=> Raise errors when dsl is misused

Cedar.xcodeproj/xcshareddata/xcschemes/Cedar-iOS StaticFramework.xcscheme, Cedar.xcodeproj/xcshareddata/xcschemes/Cedar-iOS StaticLib.xcscheme
xcodebuild requires specifying a scheme when building into a user-specified -derivedDataPath. This is common in CI workflows.
Xcode autocreates missing schemes per project settings. However, one may wish to build Cedar as a static library or framework without having to launch Xcode in order to create those schemes.
This PR adds the following schemes (autocreated):
- `Cedar-iOS StaticFramework`
- `Cedar-iOS StaticLib`
=> Add Xcode schemes for static library and framework
